FROM ubuntu:xenial-20210114
ARG version
RUN test -n "$version"
RUN apt-get update && apt-get install -y curl sudo ca-certificates --no-install-recommends \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
COPY ubuntu-generic.sh ./ubuntu-generic.sh
RUN chmod +x ubuntu-generic.sh

ENV VERSION ${version}
RUN ./ubuntu-generic.sh
